package ui

//func TestNewPager(t *testing.T) {
//	pager, err := NewPager(
//		"Lorem ipsum",
//		`
//Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Ante in nibh mauris cursus. Tortor posuere ac ut consequat semper viverra. Pretium fusce id velit ut tortor pretium viverra suspendisse. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nullam eget felis eget nunc lobortis mattis. Proin libero nunc consequat interdum varius sit amet mattis. Augue mauris augue neque gravida in fermentum et sollicitudin. Neque gravida in fermentum et sollicitudin ac orci. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eget nunc scelerisque viverra mauris.
//
//Integer malesuada nunc vel risus commodo viverra maecenas. At elementum eu facilisis sed odio morbi quis. Dictum non consectetur a erat. Pellentesque habitant morbi tristique senectus et. Neque viverra justo nec ultrices dui. In nibh mauris cursus mattis molestie a iaculis. Nulla facilisi etiam dignissim diam. In ante metus dictum at tempor commodo ullamcorper a. Id neque aliquam vestibulum morbi blandit. Eu non diam phasellus vestibulum lorem. Euismod quis viverra nibh cras.
//
//Ultrices eros in cursus turpis massa tincidunt dui ut. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Ultricies integer quis auctor elit sed vulputate mi. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Tristique senectus et netus et malesuada fames. Nunc sed blandit libero volutpat sed cras ornare arcu. Dui accumsan sit amet nulla facilisi. Aliquet enim tortor at auctor urna nunc id cursus. Scelerisque varius morbi enim nunc faucibus. Egestas fringilla phasellus faucibus scelerisque eleifend. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Aenean euismod elementum nisi quis. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Orci dapibus ultrices in iaculis nunc sed augue lacus. Magnis dis parturient montes nascetur ridiculus. Consequat nisl vel pretium lectus quam id leo. Tellus id interdum velit laoreet id donec. Viverra vitae congue eu consequat ac felis donec et.
//
//Tristique magna sit amet purus gravida quis blandit turpis cursus. Cursus metus aliquam eleifend mi in nulla. Vestibulum lectus mauris ultrices eros in cursus. Bibendum ut tristique et egestas quis ipsum suspendisse. Pharetra vel turpis nunc eget lorem dolor. Tellus elementum sagittis vitae et. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sit amet nulla facilisi morbi tempus iaculis urna id volutpat. Libero enim sed faucibus turpis in eu mi bibendum neque. Sed odio morbi quis commodo odio. Sagittis vitae et leo duis ut diam quam nulla porttitor. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Pulvinar proin gravida hendrerit lectus. In hac habitasse platea dictumst quisque sagittis. Aliquet bibendum enim facilisis gravida neque convallis a cras. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Aliquam sem et tortor consequat id. Integer enim neque volutpat ac.
//
//Interdum velit euismod in pellentesque massa placerat. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Turpis egestas sed tempus urna. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Eu mi bibendum neque egestas congue. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Viverra justo nec ultrices dui sapien eget mi proin sed. Sociis natoque penatibus et magnis dis parturient. Odio euismod lacinia at quis risus sed vulputate odio ut. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Lacus viverra vitae congue eu consequat ac felis donec et. Sit amet cursus sit amet dictum sit amet justo donec.
//
//Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Ante in nibh mauris cursus. Tortor posuere ac ut consequat semper viverra. Pretium fusce id velit ut tortor pretium viverra suspendisse. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nullam eget felis eget nunc lobortis mattis. Proin libero nunc consequat interdum varius sit amet mattis. Augue mauris augue neque gravida in fermentum et sollicitudin. Neque gravida in fermentum et sollicitudin ac orci. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eget nunc scelerisque viverra mauris.
//
//Integer malesuada nunc vel risus commodo viverra maecenas. At elementum eu facilisis sed odio morbi quis. Dictum non consectetur a erat. Pellentesque habitant morbi tristique senectus et. Neque viverra justo nec ultrices dui. In nibh mauris cursus mattis molestie a iaculis. Nulla facilisi etiam dignissim diam. In ante metus dictum at tempor commodo ullamcorper a. Id neque aliquam vestibulum morbi blandit. Eu non diam phasellus vestibulum lorem. Euismod quis viverra nibh cras.
//
//Interdum velit euismod in pellentesque massa placerat. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Turpis egestas sed tempus urna. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Eu mi bibendum neque egestas congue. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Viverra justo nec ultrices dui sapien eget mi proin sed. Sociis natoque penatibus et magnis dis parturient. Odio euismod lacinia at quis risus sed vulputate odio ut. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Lacus viverra vitae congue eu consequat ac felis donec et. Sit amet cursus sit amet dictum sit amet justo donec.
//
//Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Ante in nibh mauris cursus. Tortor posuere ac ut consequat semper viverra. Pretium fusce id velit ut tortor pretium viverra suspendisse. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nullam eget felis eget nunc lobortis mattis. Proin libero nunc consequat interdum varius sit amet mattis. Augue mauris augue neque gravida in fermentum et sollicitudin. Neque gravida in fermentum et sollicitudin ac orci. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eget nunc scelerisque viverra mauris.
//Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Ante in nibh mauris cursus. Tortor posuere ac ut consequat semper viverra. Pretium fusce id velit ut tortor pretium viverra suspendisse. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nullam eget felis eget nunc lobortis mattis. Proin libero nunc consequat interdum varius sit amet mattis. Augue mauris augue neque gravida in fermentum et sollicitudin. Neque gravida in fermentum et sollicitudin ac orci. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eget nunc scelerisque viverra mauris.
//
//Integer malesuada nunc vel risus commodo viverra maecenas. At elementum eu facilisis sed odio morbi quis. Dictum non consectetur a erat. Pellentesque habitant morbi tristique senectus et. Neque viverra justo nec ultrices dui. In nibh mauris cursus mattis molestie a iaculis. Nulla facilisi etiam dignissim diam. In ante metus dictum at tempor commodo ullamcorper a. Id neque aliquam vestibulum morbi blandit. Eu non diam phasellus vestibulum lorem. Euismod quis viverra nibh cras.
//
//Ultrices eros in cursus turpis massa tincidunt dui ut. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Ultricies integer quis auctor elit sed vulputate mi. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Tristique senectus et netus et malesuada fames. Nunc sed blandit libero volutpat sed cras ornare arcu. Dui accumsan sit amet nulla facilisi. Aliquet enim tortor at auctor urna nunc id cursus. Scelerisque varius morbi enim nunc faucibus. Egestas fringilla phasellus faucibus scelerisque eleifend. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Aenean euismod elementum nisi quis. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Orci dapibus ultrices in iaculis nunc sed augue lacus. Magnis dis parturient montes nascetur ridiculus. Consequat nisl vel pretium lectus quam id leo. Tellus id interdum velit laoreet id donec. Viverra vitae congue eu consequat ac felis donec et.
//
//Tristique magna sit amet purus gravida quis blandit turpis cursus. Cursus metus aliquam eleifend mi in nulla. Vestibulum lectus mauris ultrices eros in cursus. Bibendum ut tristique et egestas quis ipsum suspendisse. Pharetra vel turpis nunc eget lorem dolor. Tellus elementum sagittis vitae et. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sit amet nulla facilisi morbi tempus iaculis urna id volutpat. Libero enim sed faucibus turpis in eu mi bibendum neque. Sed odio morbi quis commodo odio. Sagittis vitae et leo duis ut diam quam nulla porttitor. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Pulvinar proin gravida hendrerit lectus. In hac habitasse platea dictumst quisque sagittis. Aliquet bibendum enim facilisis gravida neque convallis a cras. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Aliquam sem et tortor consequat id. Integer enim neque volutpat ac.
//
//Interdum velit euismod in pellentesque massa placerat. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Turpis egestas sed tempus urna. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Eu mi bibendum neque egestas congue. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Viverra justo nec ultrices dui sapien eget mi proin sed. Sociis natoque penatibus et magnis dis parturient. Odio euismod lacinia at quis risus sed vulputate odio ut. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Lacus viverra vitae congue eu consequat ac felis donec et. Sit amet cursus sit amet dictum sit amet justo donec.
//
//Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Ante in nibh mauris cursus. Tortor posuere ac ut consequat semper viverra. Pretium fusce id velit ut tortor pretium viverra suspendisse. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nullam eget felis eget nunc lobortis mattis. Proin libero nunc consequat interdum varius sit amet mattis. Augue mauris augue neque gravida in fermentum et sollicitudin. Neque gravida in fermentum et sollicitudin ac orci. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eget nunc scelerisque viverra mauris.
//
//Integer malesuada nunc vel risus commodo viverra maecenas. At elementum eu facilisis sed odio morbi quis. Dictum non consectetur a erat. Pellentesque habitant morbi tristique senectus et. Neque viverra justo nec ultrices dui. In nibh mauris cursus mattis molestie a iaculis. Nulla facilisi etiam dignissim diam. In ante metus dictum at tempor commodo ullamcorper a. Id neque aliquam vestibulum morbi blandit. Eu non diam phasellus vestibulum lorem. Euismod quis viverra nibh cras.
//
//Interdum velit euismod in pellentesque massa placerat. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Turpis egestas sed tempus urna. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Eu mi bibendum neque egestas congue. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Viverra justo nec ultrices dui sapien eget mi proin sed. Sociis natoque penatibus et magnis dis parturient. Odio euismod lacinia at quis risus sed vulputate odio ut. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Lacus viverra vitae congue eu consequat ac felis donec et. Sit amet cursus sit amet dictum sit amet justo donec.
//
//Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Ante in nibh mauris cursus. Tortor posuere ac ut consequat semper viverra. Pretium fusce id velit ut tortor pretium viverra suspendisse. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nullam eget felis eget nunc lobortis mattis. Proin libero nunc consequat interdum varius sit amet mattis. Augue mauris augue neque gravida in fermentum et sollicitudin. Neque gravida in fermentum et sollicitudin ac orci. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eget nunc scelerisque viverra mauris.
//Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Ante in nibh mauris cursus. Tortor posuere ac ut consequat semper viverra. Pretium fusce id velit ut tortor pretium viverra suspendisse. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nullam eget felis eget nunc lobortis mattis. Proin libero nunc consequat interdum varius sit amet mattis. Augue mauris augue neque gravida in fermentum et sollicitudin. Neque gravida in fermentum et sollicitudin ac orci. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eget nunc scelerisque viverra mauris.
//
//Integer malesuada nunc vel risus commodo viverra maecenas. At elementum eu facilisis sed odio morbi quis. Dictum non consectetur a erat. Pellentesque habitant morbi tristique senectus et. Neque viverra justo nec ultrices dui. In nibh mauris cursus mattis molestie a iaculis. Nulla facilisi etiam dignissim diam. In ante metus dictum at tempor commodo ullamcorper a. Id neque aliquam vestibulum morbi blandit. Eu non diam phasellus vestibulum lorem. Euismod quis viverra nibh cras.
//
//Ultrices eros in cursus turpis massa tincidunt dui ut. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Ultricies integer quis auctor elit sed vulputate mi. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Tristique senectus et netus et malesuada fames. Nunc sed blandit libero volutpat sed cras ornare arcu. Dui accumsan sit amet nulla facilisi. Aliquet enim tortor at auctor urna nunc id cursus. Scelerisque varius morbi enim nunc faucibus. Egestas fringilla phasellus faucibus scelerisque eleifend. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Aenean euismod elementum nisi quis. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Orci dapibus ultrices in iaculis nunc sed augue lacus. Magnis dis parturient montes nascetur ridiculus. Consequat nisl vel pretium lectus quam id leo. Tellus id interdum velit laoreet id donec. Viverra vitae congue eu consequat ac felis donec et.
//
//Tristique magna sit amet purus gravida quis blandit turpis cursus. Cursus metus aliquam eleifend mi in nulla. Vestibulum lectus mauris ultrices eros in cursus. Bibendum ut tristique et egestas quis ipsum suspendisse. Pharetra vel turpis nunc eget lorem dolor. Tellus elementum sagittis vitae et. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sit amet nulla facilisi morbi tempus iaculis urna id volutpat. Libero enim sed faucibus turpis in eu mi bibendum neque. Sed odio morbi quis commodo odio. Sagittis vitae et leo duis ut diam quam nulla porttitor. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Pulvinar proin gravida hendrerit lectus. In hac habitasse platea dictumst quisque sagittis. Aliquet bibendum enim facilisis gravida neque convallis a cras. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Aliquam sem et tortor consequat id. Integer enim neque volutpat ac.
//
//Interdum velit euismod in pellentesque massa placerat. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Turpis egestas sed tempus urna. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Eu mi bibendum neque egestas congue. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Viverra justo nec ultrices dui sapien eget mi proin sed. Sociis natoque penatibus et magnis dis parturient. Odio euismod lacinia at quis risus sed vulputate odio ut. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Lacus viverra vitae congue eu consequat ac felis donec et. Sit amet cursus sit amet dictum sit amet justo donec.
//
//Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Ante in nibh mauris cursus. Tortor posuere ac ut consequat semper viverra. Pretium fusce id velit ut tortor pretium viverra suspendisse. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nullam eget felis eget nunc lobortis mattis. Proin libero nunc consequat interdum varius sit amet mattis. Augue mauris augue neque gravida in fermentum et sollicitudin. Neque gravida in fermentum et sollicitudin ac orci. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eget nunc scelerisque viverra mauris.
//
//Integer malesuada nunc vel risus commodo viverra maecenas. At elementum eu facilisis sed odio morbi quis. Dictum non consectetur a erat. Pellentesque habitant morbi tristique senectus et. Neque viverra justo nec ultrices dui. In nibh mauris cursus mattis molestie a iaculis. Nulla facilisi etiam dignissim diam. In ante metus dictum at tempor commodo ullamcorper a. Id neque aliquam vestibulum morbi blandit. Eu non diam phasellus vestibulum lorem. Euismod quis viverra nibh cras.
//
//Interdum velit euismod in pellentesque massa placerat. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Turpis egestas sed tempus urna. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Eu mi bibendum neque egestas congue. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Viverra justo nec ultrices dui sapien eget mi proin sed. Sociis natoque penatibus et magnis dis parturient. Odio euismod lacinia at quis risus sed vulputate odio ut. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Lacus viverra vitae congue eu consequat ac felis donec et. Sit amet cursus sit amet dictum sit amet justo donec.
//
//Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Ante in nibh mauris cursus. Tortor posuere ac ut consequat semper viverra. Pretium fusce id velit ut tortor pretium viverra suspendisse. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nullam eget felis eget nunc lobortis mattis. Proin libero nunc consequat interdum varius sit amet mattis. Augue mauris augue neque gravida in fermentum et sollicitudin. Neque gravida in fermentum et sollicitudin ac orci. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eget nunc scelerisque viverra mauris.
//Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Ante in nibh mauris cursus. Tortor posuere ac ut consequat semper viverra. Pretium fusce id velit ut tortor pretium viverra suspendisse. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nullam eget felis eget nunc lobortis mattis. Proin libero nunc consequat interdum varius sit amet mattis. Augue mauris augue neque gravida in fermentum et sollicitudin. Neque gravida in fermentum et sollicitudin ac orci. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eget nunc scelerisque viverra mauris.
//
//Integer malesuada nunc vel risus commodo viverra maecenas. At elementum eu facilisis sed odio morbi quis. Dictum non consectetur a erat. Pellentesque habitant morbi tristique senectus et. Neque viverra justo nec ultrices dui. In nibh mauris cursus mattis molestie a iaculis. Nulla facilisi etiam dignissim diam. In ante metus dictum at tempor commodo ullamcorper a. Id neque aliquam vestibulum morbi blandit. Eu non diam phasellus vestibulum lorem. Euismod quis viverra nibh cras.
//
//Ultrices eros in cursus turpis massa tincidunt dui ut. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Ultricies integer quis auctor elit sed vulputate mi. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Tristique senectus et netus et malesuada fames. Nunc sed blandit libero volutpat sed cras ornare arcu. Dui accumsan sit amet nulla facilisi. Aliquet enim tortor at auctor urna nunc id cursus. Scelerisque varius morbi enim nunc faucibus. Egestas fringilla phasellus faucibus scelerisque eleifend. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Aenean euismod elementum nisi quis. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Orci dapibus ultrices in iaculis nunc sed augue lacus. Magnis dis parturient montes nascetur ridiculus. Consequat nisl vel pretium lectus quam id leo. Tellus id interdum velit laoreet id donec. Viverra vitae congue eu consequat ac felis donec et.
//
//Tristique magna sit amet purus gravida quis blandit turpis cursus. Cursus metus aliquam eleifend mi in nulla. Vestibulum lectus mauris ultrices eros in cursus. Bibendum ut tristique et egestas quis ipsum suspendisse. Pharetra vel turpis nunc eget lorem dolor. Tellus elementum sagittis vitae et. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sit amet nulla facilisi morbi tempus iaculis urna id volutpat. Libero enim sed faucibus turpis in eu mi bibendum neque. Sed odio morbi quis commodo odio. Sagittis vitae et leo duis ut diam quam nulla porttitor. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Pulvinar proin gravida hendrerit lectus. In hac habitasse platea dictumst quisque sagittis. Aliquet bibendum enim facilisis gravida neque convallis a cras. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Aliquam sem et tortor consequat id. Integer enim neque volutpat ac.
//
//Interdum velit euismod in pellentesque massa placerat. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Turpis egestas sed tempus urna. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Eu mi bibendum neque egestas congue. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Viverra justo nec ultrices dui sapien eget mi proin sed. Sociis natoque penatibus et magnis dis parturient. Odio euismod lacinia at quis risus sed vulputate odio ut. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Lacus viverra vitae congue eu consequat ac felis donec et. Sit amet cursus sit amet dictum sit amet justo donec.
//
//Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Ante in nibh mauris cursus. Tortor posuere ac ut consequat semper viverra. Pretium fusce id velit ut tortor pretium viverra suspendisse. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nullam eget felis eget nunc lobortis mattis. Proin libero nunc consequat interdum varius sit amet mattis. Augue mauris augue neque gravida in fermentum et sollicitudin. Neque gravida in fermentum et sollicitudin ac orci. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eget nunc scelerisque viverra mauris.
//
//Integer malesuada nunc vel risus commodo viverra maecenas. At elementum eu facilisis sed odio morbi quis. Dictum non consectetur a erat. Pellentesque habitant morbi tristique senectus et. Neque viverra justo nec ultrices dui. In nibh mauris cursus mattis molestie a iaculis. Nulla facilisi etiam dignissim diam. In ante metus dictum at tempor commodo ullamcorper a. Id neque aliquam vestibulum morbi blandit. Eu non diam phasellus vestibulum lorem. Euismod quis viverra nibh cras.
//
//Interdum velit euismod in pellentesque massa placerat. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Turpis egestas sed tempus urna. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Eu mi bibendum neque egestas congue. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Viverra justo nec ultrices dui sapien eget mi proin sed. Sociis natoque penatibus et magnis dis parturient. Odio euismod lacinia at quis risus sed vulputate odio ut. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Lacus viverra vitae congue eu consequat ac felis donec et. Sit amet cursus sit amet dictum sit amet justo donec.
//
//Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Ante in nibh mauris cursus. Tortor posuere ac ut consequat semper viverra. Pretium fusce id velit ut tortor pretium viverra suspendisse. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Nullam eget felis eget nunc lobortis mattis. Proin libero nunc consequat interdum varius sit amet mattis. Augue mauris augue neque gravida in fermentum et sollicitudin. Neque gravida in fermentum et sollicitudin ac orci. Et malesuada fames ac turpis egestas integer eget aliquet nibh. Eget nunc scelerisque viverra mauris.
//
//`,
//	)
//	if err != nil {
//		t.Error(err)
//	}
//
//	if err := pager.Start(); err != nil {
//		t.Error(err)
//	}
//}
